In [1]:
A = rand(3, 5)
B = rand(5, 4)
A * B

3×4 Array{Float64,2}:
 1.92459  1.20789   0.312463  0.986334
 2.12802  1.12776   0.63084   1.38877
 1.3562   0.693141  0.836933  1.23002

In [2]:
C = zeros(3, 4)
for i = 1:3, j = 1:4
    C[i,j] = sum(A[i,k] * B[k,j] for k = 1:5)
end
C

3×4 Array{Float64,2}:
 1.92459  1.20789   0.312463  0.986334
 2.12802  1.12776   0.63084   1.38877
 1.3562   0.693141  0.836933  1.23002

In [10]:
n = 100000
Float64.size * (3n - 2) / 1024 / 1024, Float64.size * n^2 / 1024 / 1024

(2.2888031005859375, 76293.9453125)

In [12]:
using Pkg
pkg"add BenchmarkTools"

   Updating registry at `~/.julia/registries/General`


   Updating git-repo `https://github.com/JuliaRegistries/General.git`


Fetching: [========================================>]  99.9 %30.8 %Fetching: [==============>                          ]  32.9 %>                 ]  55.8 %================================>        ]  78.9 %Fetching: [=====================================>   ]  92.5 %

  Resolving package versions...
  Installed JpegTurbo_jll ─ v2.0.1+1
######################################################################### 100.0%##O=#  #                                                                       
   Updating `~/.julia/environments/v1.4/Project.toml`
  [6e4b80f9] + BenchmarkTools v0.5.0
   Updating `~/.julia/environments/v1.4/Manifest.toml`
  [aacddb02] ↑ JpegTurbo_jll v2.0.1+0 ⇒ v2.0.1+1
  [458c3c95] ↑ OpenSSL_jll v1.1.1+2 ⇒ v1.1.1+4
  [83775a58] ↑ Zlib_jll v1.2.11+10 ⇒ v1.2.11+14


In [13]:
using BenchmarkTools

In [14]:
function multAx1(y, A, x)
    m, n = size(A)
    for i = 1:m
        y[i] = 0.0
        for j = 1:n
            y[i] += A[i,j] * x[j]
        end
    end
end

function multAx2(y, A, x)
    m, n = size(A)
    for i = 1:m
        y[i] = 0.0
    end
    for j = 1:n
        for i = 1:m
            y[i] += A[i,j] * x[j]
        end
    end
end

multAx2 (generic function with 1 method)

In [16]:
n = 1000
A = rand(n, n)
x = rand(n);

In [19]:
y1 = zeros(n)
y2 = zeros(n)
multAx1(y1, A, x)
multAx2(y2, A, x)
y1 ≈ y2 ≈ A * x

true

In [20]:
y = zeros(n)
@benchmark multAx1(y, $A, $x)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     2.393 ms (0.00% GC)
  median time:      2.877 ms (0.00% GC)
  mean time:        3.072 ms (0.00% GC)
  maximum time:     6.847 ms (0.00% GC)
  --------------
  samples:          1622
  evals/sample:     1

In [21]:
y = zeros(n)
@benchmark multAx2(y, $A, $x)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     945.454 μs (0.00% GC)
  median time:      1.101 ms (0.00% GC)
  mean time:        1.234 ms (0.00% GC)
  maximum time:     3.133 ms (0.00% GC)
  --------------
  samples:          4016
  evals/sample:     1

In [22]:
using SparseArrays

In [23]:
A = sprand(10, 10, 0.3)

10×10 SparseMatrixCSC{Float64,Int64} with 38 stored entries:
  [2 ,  1]  =  0.782429
  [4 ,  1]  =  0.920911
  [7 ,  1]  =  0.679593
  [8 ,  1]  =  0.372045
  [9 ,  1]  =  0.164379
  [2 ,  2]  =  0.954312
  [8 ,  2]  =  0.350904
  [1 ,  3]  =  0.318364
  [2 ,  3]  =  0.54593
  [6 ,  3]  =  0.0311635
  [7 ,  3]  =  0.904087
  [8 ,  3]  =  0.854703
  ⋮
  [2 ,  7]  =  0.962443
  [5 ,  7]  =  0.996256
  [1 ,  8]  =  0.115845
  [5 ,  9]  =  0.91093
  [6 ,  9]  =  0.111394
  [9 ,  9]  =  0.121935
  [10,  9]  =  0.791411
  [1 , 10]  =  0.510902
  [3 , 10]  =  0.25849
  [4 , 10]  =  0.901283
  [6 , 10]  =  0.16428
  [7 , 10]  =  0.694474
  [9 , 10]  =  0.288742

In [24]:
rows, cols, vals = findnz(A)

([2, 4, 7, 8, 9, 2, 8, 1, 2, 6  …  5, 6, 9, 10, 1, 3, 4, 6, 7, 9], [1, 1, 1, 1, 1, 2, 2, 3, 3, 3  …  9, 9, 9, 9, 10, 10, 10, 10, 10, 10], [0.7824285709904106, 0.9209114189441177, 0.679592973686495, 0.37204501311788474, 0.16437891324452947, 0.9543124343971525, 0.3509044228071614, 0.3183644931952152, 0.5459297015876026, 0.031163488744423207  …  0.9109298912443864, 0.1113939322722266, 0.12193543383293104, 0.7914111313531575, 0.5109022051232688, 0.2584904938732677, 0.9012829833130864, 0.16428042083819605, 0.6944735193437284, 0.2887416145676087])

**Exercício:** Fazer as 6 ordens da $C = AB$.

## Sistemas Lineares

In [25]:
A = rand(3, 3)
b = A * ones(3)

3-element Array{Float64,1}:
 1.6823950347877703
 0.6061079321048974
 1.9631716557408052

In [26]:
A \ b # Resolve Ax = b

3-element Array{Float64,1}:
 0.9999999999999997
 1.0000000000000002
 1.0000000000000002

In [50]:
A = [3.0 1 2; -1 2 1; 1 1 4]

3×3 Array{Float64,2}:
  3.0  1.0  2.0
 -1.0  2.0  1.0
  1.0  1.0  4.0

In [51]:
b = A * ones(3)

3-element Array{Float64,1}:
 6.0
 2.0
 6.0

In [52]:
m21 = A[2,1] / A[1,1]
m31 = A[3,1] / A[1,1]

# L₂ = A[2,:], L₃ = A[3,:]
A[2,2:end] = A[2,2:end] - m21 * A[1,2:end]
A[2,1] = 0.0
A[3,2:end] = A[3,2:end] - m31 * A[1,2:end]
A[3,1] = 0.0

0.0

In [53]:
b[2] = b[2] - m21 * b[1]
b[3] = b[3] - m31 * b[1]

4.0

In [54]:
A

3×3 Array{Float64,2}:
 3.0  1.0       2.0
 0.0  2.33333   1.66667
 0.0  0.666667  3.33333

In [55]:
b

3-element Array{Float64,1}:
 6.0
 4.0
 4.0

In [56]:
A \ b

3-element Array{Float64,1}:
 1.0
 1.0000000000000002
 0.9999999999999999

In [57]:
m32 = A[3,2] / A[2,2]
A[3,3:end] -= m32 * A[2,3:end]
A[3,2] = 0.0
b[3] -= m32 * b[2]

A

3×3 Array{Float64,2}:
 3.0  1.0      2.0
 0.0  2.33333  1.66667
 0.0  0.0      2.85714

In [58]:
b

3-element Array{Float64,1}:
 6.0
 4.0
 2.8571428571428568

In [59]:
A \ b

3-element Array{Float64,1}:
 1.0
 1.0000000000000002
 0.9999999999999998

In [95]:
"""
    elim_gauss!(A, b)

Modifica A e b fazendo a eliminação Gaussiana.
"""
function elim_gauss!(A, b)
    m, n = size(A)
    for j = 1:n
        cols = j+1:n
        for i = j+1:m
            mij = A[i,j] / A[j,j]
            A[i,cols] -= mij * A[j,cols]
            A[i,j] = 0.0
            b[i] -= mij * b[j]
        end
    end
end

elim_gauss!

In [105]:
A = rand(5, 5)
#A[:,3] = A[:,2] + 2 * A[:,5]
b = A * ones(5)

5-element Array{Float64,1}:
 2.3475499083281157
 2.181498799480596
 2.499556331617775
 2.4942329905205627
 2.396475772691586

In [106]:
A

5×5 Array{Float64,2}:
 0.110193  0.594594  0.433149  0.981168  0.228445
 0.185314  0.701346  0.762031  0.104157  0.428651
 0.369388  0.664129  0.275516  0.22822   0.962305
 0.258435  0.433302  0.18556   0.724783  0.892154
 0.67459   0.862213  0.575734  0.238763  0.0451755

In [107]:
elim_gauss!(A, b)

In [108]:
A

5×5 Array{Float64,2}:
 0.110193   0.594594   0.433149    0.981168   0.228445
 0.0       -0.298595   0.0335967  -1.54589    0.0444698
 0.0        0.0       -1.32602     3.82001   -0.00142394
 0.0        0.0        0.0         0.696479   0.21424
 0.0        0.0        0.0         0.0       -2.29749

In [109]:
b

5-element Array{Float64,1}:
  2.3475499083281157
 -1.7664222060379138
  2.492568216542689
  0.9107185381019871
 -2.2974860033253117

In [110]:
A \ b

5-element Array{Float64,1}:
 0.9999999999999919
 1.0000000000000016
 0.9999999999999999
 0.9999999999999994
 1.000000000000002